services:
  - type: web
    name: biblioteca
    runtime: python
    plan: free
    buildCommand: >-
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py loaddata livros &&
      python manage.py criar_admin
    startCommand: gunicorn biblioteca.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        sync: false
